services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: tt1234@
      #MYSQL_DATABASE: ${DB_NAME}
      MYSQL_DATABASE: CUSTOMERS
    command: --max-allowed-packet=1024M
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: nextjs_container
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: next_data
        target: /app/.next
    depends_on:
      - db
    links:
      - "db"

volumes:
  mysql-data:
  node_modules:
  next_data:
