services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: tt1234@
      #MYSQL_DATABASE: ${DB_NAME}
      MYSQL_DATABASE: CUSTOMERS
    command: --max-allowed-packet=1024M
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: node:23.6.1
    container_name: nextjs_container
    #command: sh -c "npm install --no-bin-links && npm run dev -- -H 0.0.0.0"
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0"
    #command: sh -c "npm config set unsafe-perm true && npm cache clean && npm install --no-bin-links && npm run dev -- -H 0.0.0.0"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      #- DB_USER=python_user
      #- DB_PASSWORD=tt1234@
      #- DB_HOST=localhost
      #- DB_NAME=CUSTOMERS
    working_dir: /app
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    depends_on:
      - db
    links:
      - "db"

volumes:
  mysql-data:
  node_modules:
